server:
  port: 8203
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-env,bus-refresh
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

data:
  env: NaN
  user:
    username: NaN
    password: NaN

spring:
  application:
    name: component
  main:
    allow-bean-definition-overriding: true
#  zipkin:
#    base-url: http://localhost:9411
#    sleuth:
#      sampler:
#        percentage: 1.0