server:
  port: 3302
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-env,bus-refresh
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true

data:
  env: NaN
  user:
    username: NaN
    password: NaN