server:
  port: 3302
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

data:
  env: NaN
  user:
    username: NaN
    password: NaN