server:
  port: 8902
spring:
  application:
    name: service-zuul
zuul:
  routes:
    base:
      path: /action/base/*
      serviceId: base
    mall:
      path: /action/mall/*
      serviceId: mall
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/