server:
  port: 8902
spring:
  application:
    name: service-zuul
zuul:
  routes:
    base:
      path: /base/*
      serviceId: base
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/