server:
  port: 8902
spring:
  application:
    name: service-zuul
  sleuth:
    sampler:
      percentage: 1.0
    zipkin:
      base-url: http://localhost:9411
zuul:
  routes:
    base:
      path: /action/base/*
      serviceId: base
    mall:
      path: /action/mall/*
      serviceId: mall
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/