server:
  port: 8094
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      routes:
        - id: BASE-SERVICE
          uri: lb://BASE
          predicates:
          - Path=/base/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/