spring:
  application:
    name: base
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0
  main:
      allow-bean-definition-overriding: true
server:
  port: 8201
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/